config/routes.rb
Rails.application.routes.draw do

  get '/admin/index'# => 'admin#index'
  get '/admin/users' => 'admin#index'
  get '/admin/posts'
  get '/admin/reviews'
  get '/admin/movies'

  delete '/admin/posts_destroy/:id' => 'admin#posts_destroy'
  delete '/admin/reviews_destroy/:id' => 'admin#reviews_destroy'
  delete '/admin/movies_destroy/:id' => 'admin#movies_destroy'

  put '/admin/change_to_manager/:id' => 'admin#change_to_manager'
  put '/admin/change_to_user/:id' => 'admin#change_to_user'

  get '/posts/privacy' => 'posts#privacy'

  resources :movies do
    member do
      post 'review'
    end
  end

  post '/movies/:id/review' => 'movies#review'

  resources :posts

  get '/posts/:id/add_comment/:user_id' => 'posts#add_comment'

  devise_for :users

  root 'movies#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/movie.rb
class Movie < ActiveRecord::Base

  mount_uploader :poster, PhotoUploader

  has_many :reviews

  def number
    self.reviews.count
  end

  def average
    sum = 0
    self.reviews.each do |review|
      sum += review.rating
    end
    if self.reviews.count == 0
      0
    else
      sum.to_f / self.reviews.count
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :image, PhotoUploader

  belongs_to :user
  has_many :comments
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :reviews
  has_many :comments
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @users = User.all
  end

  def posts
    @posts = Post.all
  end

  def posts_destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to :back, notice: "#{params[:id]}번 게시글 삭제됨"
  end

  def reviews
    @reviews = Review.all
  end

  def reviews_destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to :back, notice: "#{params[:id]}번 게시글 삭제됨"
  end

  def movies
    @movies = Movie.all
  end

  def movies_destroy
    @movies = Movie.find(params[:id])
    @movies.destroy
    redirect_to :back, notice: "#{params[:id]}번 영화 삭제됨"
  end

  def change_to_manager
    user = User.find(params[:id])
    user.update(
      role: "manager",
      nickname: "매니저"
    )
    flash[:notice] = "매니저가 되었습니다."
    redirect_to :back

  end

  def change_to_user
    user = User.find(params[:id])
    user.update(
      role: "user",
      nickname: "양민"
    )

    redirect_to :back, notice: "양민이 되었습니다."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def check_admin
    user_signed_in? && current_user.role == "admin"
  end

  def get_out
    redirect_to root_path unless check_admin
  end

  helper_method :check_admin

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :authenticate_user!, except: [:index]
  before_action :get_out, except: [:index, :show, :review]
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
  end

  def create
    Movie.create(
      title: params[:title],
      poster: params[:poster],
      genre: params[:genre],
      nation: params[:nation],
      directors: params[:directors]
    )
    redirect_to root_path
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def review
    Review.create(
      rating: params[:rating],
      comment: params[:comment],
      user_id: current_user.id,
      movie_id: params[:id],
    )
    redirect_to :back
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :privacy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_comment
    Comment.create(
      content: params[:content],
      post_id: params[:id],
      user_id: current_user.id
    )
    redirect_to :back
  end

  def privacy
    # render 'privacy'
    # render Rails.root.join('app', 'views', 'etc', 'promise.html.erb')
    render template: 'etc/promise'
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :image)#, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/index.html.erb
<main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
  <h1>관리자 홈페이지</h1>
  <h2>유저 현황</h2>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>이메일</th>
          <th>닉네임</th>
          <th>역할</th>
          <th>역할변경</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.email %></td>
            <td><%= user.nickname %></td>
            <td><%= user.role %></td>
            <td>
              <%= link_to "매니저로", "/admin/change_to_manager/#{user.id}", class: 'btn btn-primary', method: :put, data: {confirm: "매니저로 승급?"} %>
              <%= link_to "양민으로", "/admin/change_to_user/#{user.id}", class: 'btn btn-primary', method: :put, data: {confirm: "양민으로 강등?"} %><br>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</main>

app/views/admin/movies.html.erb
<main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
  <h1>관리자 페이지</h1>
  <h2>영화 현황</h2>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>제목</th>
          <th>장르</th>
          <th>국가</th>
          <th>감독</th>
          <th>포스터</th>
          <th>삭제</th>
        </tr>
      </thead>
      <tbody>
        <% @movies.each do |movie| %>
          <tr>
            <td><%= movie.id %></td>
            <td><%= movie.title %></td>
            <td><%= movie.genre %></td>
            <td><%= movie.nation %></td>
            <td><%= movie.directors %></td>
            <td><img width="30" height="30" src="<%= movie.poster %>"></td>
            <td>
              <%= link_to "삭제", "/admin/movies_destroy/#{movie.id}", method: :delete, data: {confirm: "정말 지우시겠습니까?"} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</main>

app/views/admin/posts.html.erb
<main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
  <h1>관리자 홈페이지</h1>
  <h2>게시글 현황</h2>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>제목</th>
          <th>내용</th>
          <th>글쓴이</th>
          <th>그림</th>
          <th>삭제</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.id %></td>
            <td><%= post.title %></td>
            <td><%= post.content %></td>
            <td><%= post.user.nickname %></td>
            <td><img src="<%= post.image.thumb %>"></td>
            <td>
              <%= link_to "삭제", "/admin/posts_destroy/#{post.id}", class: 'btn btn-primary', method: :delete, data: {confirm: "진짜 삭제?"} %><br>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</main>

app/views/admin/reviews.html.erb
<main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
  <h1>관리자 페이지</h1>
  <h2>리뷰 현황</h2>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>영화</th>
          <th>포스터</th>
          <th>글쓴이</th>
          <th>평점</th>
          <th>리뷰</th>
          <th>삭제</th>
        </tr>
      </thead>
      <tbody>
        <% @reviews.each do |review| %>
          <tr>
            <td><%= review.id %></td>
            <td><%= review.movie.title %></td>
            <td><img width="30" height="30" src="<%= review.movie.poster %>"></td>
            <td><%= review.user.nickname %></td>
            <td><%= review.rating %></td>
            <td><%= review.comment %></td>
            <td>
              <%= link_to "삭제", "/admin/reviews_destroy/#{review.id}", method: :delete, data: {confirm: "정말 지우시겠습니까?"} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</main>

app/views/etc/promise.html.erb
<h1>개인정보 처리방침</h1>

app/views/layouts/_admin_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Dashboard</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Settings</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Help</a>
        </li>
      </ul>
      <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
 </header>

app/views/layouts/_admin_sidebar.html.erb
<nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <a class="nav-link active" href="#">관리자 홈페이지 <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item" id="users">
      <a class="nav-link" href="/admin/users">유저관리</a>
    </li>
    <li class="nav-item" id="posts">
      <a class="nav-link" href="/admin/posts">게시판관리</a>
    </li>
    <li class="nav-item" id="reviews">
      <a class="nav-link" href="/admin/reviews">리뷰관리</a>
    </li>
    <li class="nav-item" id="movies">
      <a class="nav-link" href="/admin/movies">영화관리</a>
    </li>
  </ul>
</nav>

app/views/layouts/_header.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li class="text-white"><%= current_user.nickname if user_signed_in? %></li>
            <li><%= link_to "게시판", posts_path, class: "text-white" %></li>
            <%#= link_to "로그인", "/users/sign_in" %>
            <li><%= link_to "로그인", new_user_session_path, class: "text-white" %></li>
            <%#= link_to "로그아웃", "/users/sign_out", method: "delete" %>
            <li><%= link_to "로그아웃", destroy_user_session_path, method: "delete", class: "text-white" %></li>
            <!-- <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li> -->
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark">
    <div class="container d-flex justify-content-between">
      <a href='/' class="navbar-brand">Fake Watcha</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>관리자 페이지</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <link rel="stylesheet" href="https://getbootstrap.com/docs/4.0/examples/dashboard/dashboard.css">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/admin_header' %>

  <%= render 'layouts/admin_sidebar' %>

  <p id="notice"><%= flash[:notice] %></p>

  <div class="container-fluid">
    <div class="row">
    </div>
  </div>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Watcha</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <!-- <link rel="stylesheet" href="https://getbootstrap.com/docs/4.0/examples/album/album.css"> 스타일시트에 전역으로 적용하면 여기가 필요없다-->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <!-- <p id="notice"><%#= flash[:notice] %></p>
  <p id="alert"><%#= flash[:alert] %></p> -->
  <p id="notice"><%= notice %></p>
  <p id="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>게시판입니다</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <link rel="stylesheet" href="https://getbootstrap.com/docs/4.0/examples/dashboard/dashboard.css">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="/">Fake Watcha</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Settings</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Help</a>
        </li>
      </ul>
      <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

<%= yield %>

</body>
</html>

app/views/movies/index.html.erb
<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Watcah</h1>
      <p class="lead text-muted">영화평점 사이트 와챠</p>
      <p>
        <%= link_to "게시판", posts_path, class: "btn btn-primary"%>
        <!-- <a href="/posts" class="btn btn-primary">게시판</a> -->
        <%#= if check_admin %>
          <%= link_to "영화 추가하기", new_movie_path, class: "btn btn-secondary" if check_admin %>
          <!-- <a href="/movies/new" class="btn btn-secondary">영화 추가하기</a> -->
        <%# end %>
      </p>
    </div>
    </section>

    <div class="album text-muted">
    <div class="container">
      <div class="row">

        <% @movies.each do |movie| %>
          <div class="card">
            <img height="250px" src="<%= movie.poster %>" alt="Card image cap">
            <p class="card-title">평점: <%= movie.average == 0 ? "리뷰 없음" : movie.average  %></p>
            <a class="card-text" href="/movies/<%= movie.id %>">
                <%= movie.title %>
                <%#= movie.genre %>
                <%#= movie.nation %>
                <%#= movie.directors %>
            </a>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/movies/new.html.erb
<h1> 영화 추가하기 </h1>
<%= form_tag movies_path, method: "post", multipart: true do %>
  <p>제목 : <%= text_field_tag :title %></p><rb>
  <p>장르 : <%= text_field_tag :genre %></p><rb>
  <p>국가  : <%= text_field_tag :nation %></p><rb>
  <p>감독 : <%= text_field_tag :directors %></p><rb>
  <p>포스터 : <%= file_field_tag :poster %></p><rb>
  <%= submit_tag "영화만들기" %>
<% end %>

app/views/movies/show.html.erb
<div class="container">
  <div class="row">
    <div class="card"> <!-- col-lg-12 -->
      <img class="card-img-top" src="<%= @movie.poster %>" alt="Card image cap">
      <div class="card-body">
        <h4 class="card-title">제목: <%= @movie.title %></h4>
        <p class="card-text">장르: <%= @movie.genre %></p>
        <p class="card-text">국가: <%= @movie.nation %></p>
        <p class="card-text">감독: <%= @movie.directors %></p>
        <p class="card-text">평점: <%= @movie.average.round(2) %></p>

        <%# sum = 0 %>
        <%# @movie.reviews.each do |r| %>
          <%# sum += r.rating %>
        <%# end %>
        <!-- <p class="card-text">평점 : <%#= sum.to_f / @movie.number %></p> -->

      </div>
    </div>
  </div>
</div>

<!-- 리뷰 달기 -->
<div class="container">
  <div class="row">
    <div class="card">
      <%= form_tag("/movies/#{@movie.id}/review", method: :post) do %>
        평점 : <%= select_tag "rating", "<option>1</option><option>2</option><option>3</option><option>4</option><option>5</option>".html_safe %>
        코멘트 : <%= text_field_tag :comment %>
        <%= submit_tag "리뷰달기" %>
      <% end %>
    </div>
  </div>
</div>

<!-- 리뷰들 나열해서 보여주기 -->
<div class="container">
  <div class="row">
    <div class="card">
      <% @movie.reviews.each do |review|  %>
        <p>평점: <%= review.rating %></p>
        <p>작성자: <%= review.user.nickname %></p>
        <p>코멘트: <%= review.comment %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <!-- <div class="field"> -->
    <!-- <%#= f.label :user_id %><br> -->
    <!-- <%#= f.number_field :user_id %> -->
  <!-- </div> -->
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!-- <p id="notice"><%#= notice %></p> -->

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <!-- <td><%#= post.user_id %></td> -->
        <td><%= post.user.nickname %></td>
        <!-- user와 post에서 상호소속관계 설정하면 이렇게 쓸 수 있다. -->
        <td><%= link_to 'Show', post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<!-- <p id="notice"><%#= notice %></p> -->

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.nickname %>
</p>

<p>
  <strong>Image:</strong>
  <img src="<%= @post.image.small %>">
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<div class="card" style="width: 70rem;">
  <h4 class="card-header">댓글목록</h4>
  <form action="/posts/<%= @post.id %>/add_comment/<%= current_user.id %>">
    <div class="form-group">
      <input type="text" name="content" class="form-control" placeholder="새로운 댓글을 입력하세요">
    </div>
  </form>

  <% @post.comments.reverse.each do |cm| %>
    <ul class="list-group">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <h6 class="list-group-No"><%= cm.id %></h6>
        <p class="list-group-title"><%= cm.user.nickname %></p>
        <h4 class="list-group-text"><%= cm.content %></h4>
        <p class="list-group-text"><%= cm.created_at %></p>
      </li>
    </ui>
  <% end %>
</div>